### ISSUE TITLE
Discovery server crashes when log file gets too large

### ISSUE THREAD

**Issue by gz-c** [skycoin/skywire-testnet#128]
When the log file gets too large, the discovery server crashes with an "out of memory" error.
This was seen when the log file exceeded 2GB on a server with less than 2GB.
The log system should not be holding on the entire logs in memory, and should not be reading the entire logs into memory when starting.

The problem can be mitigated by adjusting `discovery.log.conf` to set a `max-size` for log files. See https://github.com/gogap/logrus_mate for details on configuring the log file.

```
$ ./discovery -web-port :8001 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb698ec, 0x16)
	/home/user/GOROOT/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc420300000, 0x82c40000, 0x433900, 0x1250338)
	/home/user/GOROOT/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x12364a0, 0x82c40000, 0x7fc33cf82fe8)
	/home/user/GOROOT/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x12364a0, 0x4161a, 0x0)
	/home/user/GOROOT/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x12364a0, 0x4161a, 0x1250348, 0x7fc33be3fde8)
	/home/user/GOROOT/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x12364a0, 0x4161a, 0x7fc33be30101, 0x42bb2a)
	/home/user/GOROOT/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/home/user/GOROOT/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x12364a0, 0x4161a, 0x7fc33c010101, 0x7fc33cf7b0f0)
	/home/user/GOROOT/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x82c32521, 0xaa0101, 0xaa2c60)
	/home/user/GOROOT/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/home/user/GOROOT/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/home/user/GOROOT/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/home/user/GOROOT/src/runtime/proc.go:1175

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/user/GOROOT/src/runtime/asm_amd64.s:363 fp=0xc4201336e8 sp=0xc4201336e0 pc=0x45bf70
runtime.mallocgc(0x82c32521, 0xa74740, 0x418901, 0xc4201337c0)
	/home/user/GOROOT/src/runtime/malloc.go:720 +0x8a2 fp=0xc420133788 sp=0xc4201336e8 pc=0x418f22
runtime.makeslice(0xa74740, 0x82c32521, 0x82c32521, 0x8, 0x68, 0xc420187c00)
	/home/user/GOROOT/src/runtime/slice.go:61 +0x77 fp=0xc4201337b8 sp=0xc420133788 pc=0x448017
bytes.makeSlice(0x82c32521, 0x0, 0x0, 0x0)
	/home/user/GOROOT/src/bytes/buffer.go:230 +0x6d fp=0xc4201337f8 sp=0xc4201337b8 pc=0x4e832d
bytes.(*Buffer).grow(0xc420187c00, 0x82c32521, 0xc420133878)
	/home/user/GOROOT/src/bytes/buffer.go:144 +0x151 fp=0xc420133848 sp=0xc4201337f8 pc=0x4e7ce1
bytes.(*Buffer).Grow(0xc420187c00, 0x82c32521)
	/home/user/GOROOT/src/bytes/buffer.go:163 +0x3a fp=0xc420133870 sp=0xc420133848 pc=0x4e7e8a
io/ioutil.readAll(0xc08720, 0xc42000e6d0, 0x82c32521, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/GOROOT/src/io/ioutil/ioutil.go:34 +0x93 fp=0xc4201338b8 sp=0xc420133870 pc=0x58b563
io/ioutil.ReadFile(0xc420026e80, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/GOROOT/src/io/ioutil/ioutil.go:73 +0xd5 fp=0xc420133910 sp=0xc4201338b8 pc=0x58b775
github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file.(*FileLogWriter).initFd(0xc420187b90, 0xc42000e6c8, 0x0)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file/file.go:153 +0x14d fp=0xc420133978 sp=0xc420133910 pc=0x80162d
github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file.(*FileLogWriter).startLogger(0xc420187b90, 0x1, 0xc4200847d0)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file/file.go:105 +0x5e fp=0xc4201339a8 sp=0xc420133978 pc=0x8010de
github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file.(*FileLogWriter).Init(0xc420187b90, 0xc420026e80, 0xd, 0x0, 0x0, 0x1, 0x7, 0x1, 0x3, 0xafb3e0, ...)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file/file.go:94 +0xbe fp=0xc4201339d0 sp=0xc4201339a8 pc=0x80102e
github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file.NewFileHook(0xc11ca0, 0xc42000e6c0, 0xc420026e70, 0x4, 0xc420171cf8, 0xc42000e601)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks/file/hook.go:42 +0x1c5 fp=0xc420133aa8 sp=0xc4201339d0 pc=0x801f55
github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate.NewHook(0xc420026e70, 0x4, 0xc11ca0, 0xc42000e6c0, 0x0, 0x0, 0x0, 0x0)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/hooks.go:57 +0x177 fp=0xc420133b00 sp=0xc420133aa8 pc=0x7f9557
github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate.hijackByConfig(0xc420084140, 0xc11ca0, 0xc42000e6a0, 0xc11ca0, 0xc42000e6a0)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/logrus_mate.go:85 +0x586 fp=0xc420133ca0 sp=0xc420133b00 pc=0x7f9b46
github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate.(*LogrusMate).Hijack(0xc4202397d0, 0xc420084140, 0xb6195b, 0x9, 0x0, 0x0, 0x0, 0x40cbbb, 0xc4201d84e0)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/gogap/logrus_mate/logrus_mate.go:168 +0x1f3 fp=0xc420133d20 sp=0xc420133ca0 pc=0x7fa3c3
github.com/skycoin/skywire/discovery.New(0xc4201e3080, 0x26, 0xb5ed47, 0x5, 0x7ffee90bb7f5, 0x5, 0xc4201d8480, 0x58, 0xc420238750)
	/home/user/GOPATH/src/github.com/skycoin/skywire/discovery/discovery.go:37 +0x179 fp=0xc420133e70 sp=0xc420133d20 pc=0x970fa9
main.main()
	/home/user/GOPATH/src/github.com/skycoin/skywire/cmdx/discovery/main.go:61 +0x1eb fp=0xc420133f88 sp=0xc420133e70 pc=0x9725bb
runtime.main()
	/home/user/GOROOT/src/runtime/proc.go:198 +0x212 fp=0xc420133fe0 sp=0xc420133f88 pc=0x433ac2
runtime.goexit()
	/home/user/GOROOT/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420133fe8 sp=0xc420133fe0 pc=0x45eae1

goroutine 5 [runnable]:
github.com/skycoin/skywire/vendor/github.com/astaxie/beego/session.(*Manager).GC(0xc4200f7b20)
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/astaxie/beego/session/session.go:272
created by github.com/skycoin/skywire/vendor/github.com/skycoin/net/skycoin-messenger/monitor.init.0
	/home/user/GOPATH/src/github.com/skycoin/skywire/vendor/github.com/skycoin/net/skycoin-messenger/monitor/monitor.go:37 +0xe8

goroutine 6 [runnable]:
os/signal.loop()
	/home/user/GOROOT/src/os/signal/signal_unix.go:20
created by os/signal.init.0
	/home/user/GOROOT/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [runnable, locked to thread]:
runtime.gopark(0xb89750, 0xc4201d8538, 0xb6190a, 0x9, 0xc42002ce16, 0x3)
	/home/user/GOROOT/src/runtime/proc.go:291 +0x11a
runtime.goparkunlock(0xc4201d8538, 0xb6190a, 0x9, 0x16, 0x3)
	/home/user/GOROOT/src/runtime/proc.go:297 +0x5e
runtime.chansend(0xc4201d84e0, 0xc420040f40, 0xc420040f01, 0x45b5f2, 0x8)
	/home/user/GOROOT/src/runtime/chan.go:234 +0x25b
runtime.chansend1(0xc4201d84e0, 0xc420040f40)
	/home/user/GOROOT/src/runtime/chan.go:125 +0x35
runtime.ensureSigM.func1()
	/home/user/GOROOT/src/runtime/signal_unix.go:560 +0x152
runtime.goexit()
	/home/user/GOROOT/src/runtime/asm_amd64.s:2361 +0x1
```

**Comment by gz-c** [comment]
Fixed by #131 by removing logrus_mate
