### ISSUE TITLE
add transport failure

### ISSUE THREAD

**Issue by ivcosla** [skycoin/skywire-testnet#216]
Add transport fails with `EOF` and makes `skywire-node` fail with the following message:

```bash
2019/03/12 08:27:22 Invalid public key
panic: Invalid public key

goroutine 27 [running]:
log.Panic(0xc0004a28c8, 0x1, 0x1)
	/usr/local/go/src/log/log.go:333 +0xac
github.com/skycoin/skycoin/src/cipher.MustNewPubKey(0xc0000a2120, 0x21, 0x21, 0x0, 0x0, 0x0, 0x0, 0x2fac2041dc988000)
	/Users/ivan/Desktop/skycoin/pkg/mod/github.com/skycoin/skycoin@v0.25.1/src/cipher/crypto.go:112 +0xe1
github.com/skycoin/skywire/internal/noise.Secp256k1.DH(0xc000310680, 0x20, 0x20, 0xc0000a2120, 0x21, 0x21, 0x0, 0x80, 0x0)
	/Users/ivan/Desktop/mainnet/skywire/internal/noise/dh.go:25 +0x5a
github.com/flynn/noise.(*HandshakeState).ReadMessage(0xc0000c4680, 0x0, 0x0, 0x0, 0xc00039e023, 0x10, 0x10, 0x13e9dd9, 0xc0003e81f0, 0xc000472150, ...)
	/Users/ivan/Desktop/skycoin/pkg/mod/github.com/flynn/noise@v0.0.0-20180327030543-2492fe189ae6/state.go:445 +0x36d
github.com/skycoin/skywire/internal/noise.(*Noise).ProcessMessage(0xc0000c2750, 0xc00039e002, 0x31, 0x31, 0x3, 0x3)
	/Users/ivan/Desktop/mainnet/skywire/internal/noise/noise.go:105 +0x89
github.com/skycoin/skywire/pkg/messaging.(*Client).onData(0xc000132dc0, 0xc0002e6060, 0xc000116e01, 0xc00039e001, 0x32, 0x32, 0x0, 0x33)
	/Users/ivan/Desktop/mainnet/skywire/pkg/messaging/client.go:302 +0xa8e
github.com/skycoin/skywire/pkg/messaging.(*Pool).messageAction.func2(0xc0002e6060, 0x1514401, 0xc00039e001, 0x32, 0x32, 0x2, 0x3300c000116f00)
	/Users/ivan/Desktop/mainnet/skywire/pkg/messaging/pool.go:215 +0x56
github.com/skycoin/skywire/pkg/messaging.(*Link).readFrame(...)
	/Users/ivan/Desktop/mainnet/skywire/pkg/messaging/link.go:186
github.com/skycoin/skywire/pkg/messaging.(*Link).handleData(0xc0002e6060, 0xc00039e000, 0x33, 0x33, 0x35, 0x0, 0x0, 0x0, 0x1f)
	/Users/ivan/Desktop/mainnet/skywire/pkg/messaging/link.go:169 +0x13f
github.com/skycoin/skywire/pkg/messaging.(*Link).readLoop(0xc0002e6060, 0xc000330000, 0xc0001c40a0)
	/Users/ivan/Desktop/mainnet/skywire/pkg/messaging/link.go:152 +0xa9
github.com/skycoin/skywire/pkg/messaging.(*Link).Open.func1(0xc0002e6060, 0xc0004ac000, 0xc00017a178)
	/Users/ivan/Desktop/mainnet/skywire/pkg/messaging/link.go:85 +0x2f
created by github.com/skycoin/skywire/pkg/messaging.(*Link).Open
	/Users/ivan/Desktop/mainnet/skywire/pkg/messaging/link.go:83 +0x20f
```

Seems an encryption failure.

**Comment by ivcosla** [comment]
Fixed with #217
