### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by VictorNine** [skycoin/skywire-testnet#31]
Hi! I'm having some trouble building width docker.

I've clone the repo and used "docker build -t skycoin/skywire .

Error:
```
ERROR in ./src/styles.scss 
Module build failed: Error: Can't resolve '~@angular/material/prebuilt-themes/deeppurple-amber.css' in '/home/node/net/skycoin-messenger/monitor/web/src' 
   at onError (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:61:15) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at runAfter (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:158:4) 
   at innerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:146:3) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at next (/home/node/net/skycoin-messenger/monitor/web/node_modules/tapable/lib/Tapable.js:252:11) 
   at /home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at runAfter (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:158:4) 
   at innerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:146:3) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at next (/home/node/net/skycoin-messenger/monitor/web/node_modules/tapable/lib/Tapable.js:252:11) 
   at innerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:144:11) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at next (/home/node/net/skycoin-messenger/monitor/web/node_modules/tapable/lib/Tapable.js:249:35) 
   at resolver.doResolve.createInnerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6) 
 @ multi ./src/styles.scss 
ERROR in ./src/styles.scss 
Module build failed: ModuleBuildError: Module build failed: Error: Can't resolve '~@angular/material/prebuilt-themes/deeppurple-amber.css' in '/home/node/net/skycoin-messenger/monitor/web/src' 
   at onError (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:61:15) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at runAfter (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:158:4) 
   at innerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:146:3) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at next (/home/node/net/skycoin-messenger/monitor/web/node_modules/tapable/lib/Tapable.js:252:11) 
   at /home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at runAfter (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:158:4) 
   at innerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:146:3) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at next (/home/node/net/skycoin-messenger/monitor/web/node_modules/tapable/lib/Tapable.js:252:11) 
   at innerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/Resolver.js:144:11) 
   at loggingCallbackWrapper (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19) 
   at next (/home/node/net/skycoin-messenger/monitor/web/node_modules/tapable/lib/Tapable.js:249:35) 
   at resolver.doResolve.createInnerCallback (/home/node/net/skycoin-messenger/monitor/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6) 
   at runLoaders (/home/node/net/skycoin-messenger/monitor/web/node_modules/webpack/lib/NormalModule.js:195:19) 
   at /home/node/net/skycoin-messenger/monitor/web/node_modules/loader-runner/lib/LoaderRunner.js:364:11 
   at /home/node/net/skycoin-messenger/monitor/web/node_modules/loader-runner/lib/LoaderRunner.js:230:18 
   at context.callback (/home/node/net/skycoin-messenger/monitor/web/node_modules/loader-runner/lib/LoaderRunner.js:111:13) 
   at Promise.resolve.then.then.catch (/home/node/net/skycoin-messenger/monitor/web/node_modules/postcss-loader/lib/index.js:189:71) 
   at <anonymous> 
   at process._tickCallback (internal/process/next_tick.js:188:7) 
 @ ./src/styles.scss 
 @ multi ./src/styles.scss 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! skywire-manager-ui@0.0.3 build-m: `ng build --prod --env=manager -op dist-manager` 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the skywire-manager-ui@0.0.3 build-m script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!    /root/.npm/_logs/2018-01-16T09_04_18_034Z-debug.log 
./tool.sh: line 52: err: command not found 
```

**Comment by gz-c** [comment]
@etiennetremel any idea?

**Comment by etiennetremel** [comment]
@VictorNine, recently I have seen a few changes in the skycoin/net repository that could have caused these errors.
I just tried on with latest master and didn't hit this problem. Could you try again using Docker and let us know if the build pass?
We might need to pin the version of the skycoin/net dependency.

**Comment by VictorNine** [comment]
Pulled the latest changes and now it works
