### ISSUE TITLE
Bug: skywire-node exits with panic when messaging-server is down

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#405]
**Describe the bug**

Start messaging between nodes and stop messaging-server during process.

NodeA and NodeC will exit with panic:
```
goroutine 47 [running]:
github.com/skycoin/skywire/pkg/messaging.(*chanList).add(0xc00015ae20, 0xc000366000, 0xea8f1fe9b8855e00)
        /home/isk/github.com/skycoin/src/skywire/pkg/messaging/chan_list.go:23 +0x12a
github.com/skycoin/skywire/pkg/messaging.(*MsgFactory).Dial(0xc0001f20c0, 0xd57c80, 0xc000030158, 0x55a01c541c94803, 0x7fe5f28a23ff55c4, 0x4b6aa99c314f9b8, 0xc1a4912bb3b5abe9, 0xc0002d5bfe, 0x1, 0x1, ...)
        /home/isk/github.com/skycoin/src/skywire/pkg/messaging/factory.go:164 +0x6fb
github.com/skycoin/skywire/pkg/transport.(*Manager).dialTransport(0xc0001a21e0, 0xd57c80, 0xc000030158, 0xd59080, 0xc0001f20c0, 0x55a01c541c94803, 0x7fe5f28a23ff55c4, 0x4b6aa99c314f9b8, 0xc1a4912bb3b5abe9, 0xc0002801fe, ...)
        /home/isk/github.com/skycoin/src/skywire/pkg/transport/manager.go:296 +0x17e
github.com/skycoin/skywire/pkg/transport.(*Manager).manageTransport(0xc0001a21e0, 0xd57c80, 0xc000030158, 0xc0001a0880, 0xd59080, 0xc0001f20c0, 0x55a01c541c94803, 0x7fe5f28a23ff55c4, 0x4b6aa99c314f9b8, 0xc1a4912bb3b5abe9, ...)
        /home/isk/github.com/skycoin/src/skywire/pkg/transport/manager.go:426 +0xf60
created by github.com/skycoin/skywire/pkg/transport.(*Manager).createTransport
        /home/isk/github.com/skycoin/src/skywire/pkg/transport/manager.go:335 +0x986
```

**Environment information:**

Must be irrelevant.

```bash
$ uname -a                                                                                                                                           8:47:29
Linux air 5.2.0-1-MANJARO #1 SMP PREEMPT Tue May 21 15:08:23 UTC 2019 x86_64 GNU/Linux
```
**Steps to Reproduce**

In skywire-services
```bash 
$ make integration-build
$ make integration-run-messaging
$ ./integration/startup.sh
$ ./integration/test-messaging.sh # Ensure that messaging works
$ ./integration/test-messaging-loop.sh 
```

Now switch to tmux window 2:MSG and Ctrl-C.
Switch to tmux window 6:NodeA and observe panic

**Actual behavior**

Exit with panic, leaving skychat running.
Restart of messaging-server does not restores messaging.

**Expected behavior**

Stop of communication without exit.
Restart of messaging-server must restore messaging.

**Additional context**

After attempt to:
- kill hanged skychats
- restart of NodeA and NodeC

```bash
$ ./integration/startup.sh                                                                                                                           
[2019-06-13T08:59:37+03:00] FATAL [skywire-cli]: remote has no DelegatedServers
[2019-06-13T08:59:37+03:00] FATAL [skywire-cli]: remote has no DelegatedServers
\nNodeA Transports:
type     id     remote     mode
\nNodeB Transports:
type          id                                       remote                                                                 mode
messaging     a13b7256-8c99-5a47-b82c-982d9edb5442     02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1     setup
```

**Possible implementation**

Needs investigation

**Comment by evanlinjin** [comment]
As this is a messaging-related bug, I don't think it is relevant.

**Comment by ayuryshev** [comment]
dmgs can't live with messaging-server restart too

**Comment by evanlinjin** [comment]
> dmgs can't live with messaging-server restart too

From my experience, `dmsg` does not panic when `dmsg`'s `messaging-server` restarts. However, there seems to be a bug where `dmsg.Client` doesn't update it's entry when reconnected to the server (but that's a separate issue).

**Comment by evanlinjin** [comment]
#406
