### ISSUE TITLE
Another set of panics.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#487]
On commit: 4073c3b7ce2d780e7a58c0354a7d3a30b08d7abd
```
[2019-07-16T23:46:12+08:00] INFO [trmanager]: Spawned manageTransport for mTr.ID: 27cc7d72-88de-5342-8da3-c7a9cd29b2b0. mgrQty: 2 PK: 02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:12+08:00] INFO [dmsg]: Injected [FWD] bufSize="117/65535" received=<type:FWD><id:36247><size:119><seq:9067> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:12+08:00] INFO [router]: Got new Setup request with type LoopClosed
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]: panic: runtime error: invalid memory address or nil pointer dereference
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9a4743]
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]:
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]: goroutine 208943 [running]:
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]: github.com/skycoin/skywire/pkg/app.(*App).closeConn(0xc0000aa780, 0xc000038542, 0x69, 0x69, 0x4, 0xc0002e23c0)
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/app.go:225 +0x1e3
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]: github.com/skycoin/skywire/pkg/app.(*App).handleProto.func1(0x482b04, 0xc000038542, 0x69, 0x69, 0xc0000d66e0, 0x7efbff58b180, 0xc0000d66e0, 0xb43601)
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/app.go:159 +0x80
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]: github.com/skycoin/skywire/pkg/app.(*Protocol).Serve.func1(0xc00017c000, 0xc0000c0a40, 0x400, 0xc000038540, 0x6b, 0x6b)
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/protocol.go:116 +0x91
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]: created by github.com/skycoin/skywire/pkg/app.(*Protocol).Serve
[2019-07-16T23:46:12+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/protocol.go:110 +0x1ce
[2019-07-16T23:46:12+08:00] INFO [dmsg]: (HANDSHAKE) Accepted by remote. remote=0348c941c5015a05c455ff238af2e57fb8f914c399aab604e9abb5b32b91a4c1fe
[2019-07-16T23:46:12+08:00] INFO [dmsg]: Injected [ACK] received=<type:ACK><id:35748><size:2><seq:29346> remoteClient=0348c941c5015a05c455ff238af2e57fb8f914c399aab604e9abb5b32b91a4c1fe
[2019-07-16T23:46:12+08:00] INFO [dmsg]: Injected [FWD] bufSize="515/65535" received=<type:FWD><id:35748><size:517><seq:8068> remoteClient=0348c941c5015a05c455ff238af2e57fb8f914c399aab604e9abb5b32b91a4c1fe
[2019-07-16T23:46:12+08:00] INFO [trmanager]: Updating transport f531c4a4-013d-59ea-866d-03747b51b914
==================
WARNING: DATA RACE
Write at 0x00c000210000 by goroutine 83:
  github.com/skycoin/skywire/pkg/transport.(*ManagedTransport).updateTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/managed_transport.go:104 +0x72
  github.com/skycoin/skywire/pkg/transport.(*Manager).manageTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:464 +0xfc9

Previous read at 0x00c000210000 by goroutine 84:
  [failed to restore the stack]

Goroutine 83 (running) created at:
  github.com/skycoin/skywire/pkg/transport.(*Manager).createTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:326 +0x934
  github.com/skycoin/skywire/pkg/visor.(*RPC).AddTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:223 +0x225
  runtime.call64()
      /snap/go/4098/src/runtime/asm_amd64.s:520 +0x3a
  reflect.Value.Call()
      /snap/go/4098/src/reflect/value.go:308 +0xc0
  net/rpc.(*service).call()
      /snap/go/4098/src/net/rpc/server.go:384 +0x21c

Goroutine 84 (finished) created at:
  github.com/skycoin/skywire/pkg/router.(*Router).Serve.func1()
      /home/evanlinjin/GolandProjects/skywire/pkg/router/router.go:99 +0x30c
==================
[2019-07-16T23:46:12+08:00] INFO [trmanager]: manageTransport exit for f531c4a4-013d-59ea-866d-03747b51b914. mgrQty: 1
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: 2019/07/16 23:46:22 [ERR] yamux: keepalive failed: i/o deadline reached
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: 2019/07/16 23:46:22 Failed to start SOCKS5 server: keepalive timeout
[2019-07-16T23:46:22+08:00] INFO [router]: Got new App request with type Close: {"port":3,"remote":{"pk":"031b80cd5773143a39d940dc0710b93dcccc262a85108018a7a95ab9af734f8055","port":10}}
[2019-07-16T23:46:22+08:00] INFO [dmsg]: (HANDSHAKE) Accepted by remote. remote=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:22+08:00] INFO [trmanager]: Dialed to 02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1 using dmsg factory. Transport ID: 27cc7d72-88de-5342-8da3-c7a9cd29b2b0
[2019-07-16T23:46:22+08:00] INFO [trmanager]: manageTransport exit for 27cc7d72-88de-5342-8da3-c7a9cd29b2b0. mgrQty: 0
[2019-07-16T23:46:22+08:00] INFO [router]: New transport: isAccepted: false, isSetup: true
[2019-07-16T23:46:22+08:00] INFO [trmanager]: Spawned manageTransport for mTr.ID: 27cc7d72-88de-5342-8da3-c7a9cd29b2b0. mgrQty: 1 PK: 02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:22+08:00] INFO [dmsg]: Injected [ACK] received=<type:ACK><id:35750><size:2><seq:16565> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:22+08:00] INFO [dmsg]: Injected [FWD] bufSize="7/65535" received=<type:FWD><id:35750><size:9><seq:39830> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:22+08:00] INFO [router]: Closed loop :3 <-> 031b80cd5773143a39d940dc0710b93dcccc262a85108018a7a95ab9af734f8055:10
[2019-07-16T23:46:22+08:00] INFO [trmanager]: manageTransport exit for 27cc7d72-88de-5342-8da3-c7a9cd29b2b0. mgrQty: 0
[2019-07-16T23:46:22+08:00] INFO [dmsg]: (HANDSHAKE) Accepted locally. remote=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:22+08:00] INFO [trmanager]: Accepted new transport with type dmsg from 02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1. ID: 27cc7d72-88de-5342-8da3-c7a9cd29b2b0
[2019-07-16T23:46:22+08:00] INFO [dmsg]: Accepted [REQUEST] received=<type:REQUEST><id:36249><size:66> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1 remoteServer=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2019-07-16T23:46:22+08:00] INFO [router]: New transport: isAccepted: true, isSetup: true
[2019-07-16T23:46:22+08:00] INFO [trmanager]: Spawned manageTransport for mTr.ID: 27cc7d72-88de-5342-8da3-c7a9cd29b2b0. mgrQty: 1 PK: 02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:22+08:00] INFO [dmsg]: Injected [FWD] bufSize="117/65535" received=<type:FWD><id:36249><size:119><seq:3624> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1
[2019-07-16T23:46:22+08:00] INFO [router]: Got new Setup request with type LoopClosed
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: panic: runtime error: invalid memory address or nil pointer dereference
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5f42d3]
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]:
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: goroutine 808 [running]:
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: github.com/skycoin/skywire/pkg/app.(*App).closeConn(0xc0000c23c0, 0xc00002a1c2, 0x69, 0x69, 0x1, 0x57ac6e)
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]:     /home/evanlinjin/GolandProjects/skywire/pkg/app/app.go:225 +0x1e3
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: github.com/skycoin/skywire/pkg/app.(*App).handleProto.func1(0x481304, 0xc00002a1c2, 0x69, 0x69, 0xc0001240c0, 0xc, 0xc, 0x0)
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]:     /home/evanlinjin/GolandProjects/skywire/pkg/app/app.go:159 +0x80
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: github.com/skycoin/skywire/pkg/app.(*Protocol).Serve.func1(0xc000012020, 0xc0000b27c0, 0x400, 0xc00002a1c0, 0x6b, 0x6b)
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]:     /home/evanlinjin/GolandProjects/skywire/pkg/app/protocol.go:116 +0x91
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]: created by github.com/skycoin/skywire/pkg/app.(*Protocol).Serve
[2019-07-16T23:46:22+08:00] INFO [socksproxy.v1.0]:     /home/evanlinjin/GolandProjects/skywire/pkg/app/protocol.go:110 +0x1ce
```

**Comment by nkryuchkov** [comment]
TODO: Need to check if it may be reproduced on the`mainnet` branch.
