### ISSUE TITLE
App and routing related panics.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#489]
```
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]: panic: runtime error: invalid memory address or nil pointer dereference
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9ba0e8]
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]:
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]: goroutine 366 [running]:
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]: github.com/skycoin/skywire/pkg/app.(*App).closeConn(0xc0000d07e0, 0xc0000340c2, 0xbd, 0xbd, 0xc0002af6d0, 0x4575bc)
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/app.go:246 +0x2a8
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]: github.com/skycoin/skywire/pkg/app.(*App).handleProto.func1(0x482b04, 0xc0000340c2, 0xbd, 0xbd, 0x468f9f, 0xc0004dc480, 0x4, 0xc0004dc480)
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/app.go:174 +0x80
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]: github.com/skycoin/skywire/pkg/app.(*Protocol).Serve.func1(0xc000020020, 0xc0000bcd40, 0x400, 0xc0000340c0, 0xbf, 0xbf)
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/protocol.go:118 +0xab
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]: created by github.com/skycoin/skywire/pkg/app.(*Protocol).Serve
[2019-07-18T16:21:45+08:00] INFO [skychat.v1.0]:        /home/evanlinjin/GolandProjects/skywire/pkg/app/protocol.go:110 +0x1ce

```

**Comment by evanlinjin** [comment]
```
==================
WARNING: DATA RACE
Write at 0x00c00028b6f0 by goroutine 76:
  github.com/skycoin/skywire/pkg/transport.(*Manager).acceptTransport.func1()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:339 +0x67

Previous read at 0x00c00028b6f0 by goroutine 41:
  github.com/skycoin/skywire/pkg/transport.(*Manager).acceptTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:343 +0xed1
  github.com/skycoin/skywire/pkg/transport.(*Manager).Serve.func1()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:189 +0x1fd

Goroutine 76 (running) created at:
  github.com/skycoin/skywire/pkg/transport.(*Manager).acceptTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:338 +0xec0
  github.com/skycoin/skywire/pkg/transport.(*Manager).Serve.func1()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:189 +0x1fd

Goroutine 41 (finished) created at:
  github.com/skycoin/skywire/pkg/transport.(*Manager).Serve()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:178 +0x1ea
  github.com/skycoin/skywire/pkg/router.(*Router).Serve()
      /home/evanlinjin/GolandProjects/skywire/pkg/router/router.go:128 +0x14e
  github.com/skycoin/skywire/pkg/visor.(*Node).Start()
      /home/evanlinjin/GolandProjects/skywire/pkg/visor/visor.go:245 +0x6ae
  github.com/skycoin/skywire/cmd/skywire-visor/commands.(*runCfg).runNode.func1()
      /home/evanlinjin/GolandProjects/skywire/cmd/skywire-visor/commands/root.go:152 +0x3c
==================

```

**Comment by evanlinjin** [comment]
```
==================
WARNING: DATA RACE
Write at 0x00c0001a3110 by goroutine 56:
  github.com/skycoin/skywire/pkg/transport.(*ManagedTransport).updateTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/managed_transport.go:104 +0x72
  github.com/skycoin/skywire/pkg/transport.(*Manager).manageTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:458 +0xfc8

Previous read at 0x00c0001a3110 by goroutine 57:
  github.com/skycoin/skywire/pkg/transport.(*ManagedTransport).Close()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/managed_transport.go:90 +0x4f
  github.com/skycoin/skywire/pkg/router.(*Router).Serve.func1.1.1()
      /home/evanlinjin/GolandProjects/skywire/pkg/router/router.go:103 +0x42
  github.com/skycoin/skywire/pkg/router.(*Router).Serve.func1.1()
      /home/evanlinjin/GolandProjects/skywire/pkg/router/router.go:112 +0x1b5

Goroutine 56 (running) created at:
  github.com/skycoin/skywire/pkg/transport.(*Manager).createTransport()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:321 +0x934
  github.com/skycoin/skywire/pkg/transport.(*Manager).reconnectTransports()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:118 +0x59c
  github.com/skycoin/skywire/pkg/transport.(*Manager).Serve()
      /home/evanlinjin/GolandProjects/skywire/pkg/transport/manager.go:172 +0x6a
  github.com/skycoin/skywire/pkg/router.(*Router).Serve()
      /home/evanlinjin/GolandProjects/skywire/pkg/router/router.go:128 +0x14e
  github.com/skycoin/skywire/pkg/visor.(*Node).Start()
      /home/evanlinjin/GolandProjects/skywire/pkg/visor/visor.go:245 +0x6ae
  github.com/skycoin/skywire/cmd/skywire-visor/commands.(*runCfg).runNode.func1()
      /home/evanlinjin/GolandProjects/skywire/cmd/skywire-visor/commands/root.go:152 +0x3c

Goroutine 57 (finished) created at:
  github.com/skycoin/skywire/pkg/router.(*Router).Serve.func1()
      /home/evanlinjin/GolandProjects/skywire/pkg/router/router.go:101 +0x30c
==================
```
